# Generated by Django 2.2.1 on 2019-06-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery_store',
            name='location',
        ),
        migrations.RemoveField(
            model_name='grocery_store',
            name='owner',
        ),
    ]
