# Generated by Django 2.2.1 on 2019-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20190604_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_store',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='grocery_store',
            name='owner',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='grocery_store',
            name='store_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
